[build]
builder = "NIXPACKS"

[[services]]
name = "backend"
source = "backend"
healthcheckPath = "/api/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[[services]]
name = "frontend" 
source = "frontend"
